# =============================================================================
# lib/cmd_init.sh — generate cluster.env from defaults + flags, prep the host
#
# Run once per node, before bootstrap. Refuses to overwrite an existing
# cluster.env (use --overwrite if you really mean it). Auto-generates a
# MinIO secret key if one isn't provided.
# =============================================================================

[[ -n "${_CMD_INIT_SH_LOADED:-}" ]] && return 0
_CMD_INIT_SH_LOADED=1

cmd_init() {
  # User-settable values (others available via direct cluster.env edit).
  local peer_ips=""
  local cluster_name="milvus-onprem"
  local milvus_image_tag="v2.6.11"
  local minio_secret_key=""
  local data_root="/data"
  local milvus_port="" lb_port="" etcd_client_port="" etcd_peer_port=""
  local minio_api_port="" pair_port=""
  local overwrite=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --peer-ips=*)            peer_ips="${1#*=}"; shift ;;
      --peer-ips)              peer_ips="$2"; shift 2 ;;
      --cluster-name=*)        cluster_name="${1#*=}"; shift ;;
      --milvus-image-tag=*)    milvus_image_tag="${1#*=}"; shift ;;
      --minio-secret-key=*)    minio_secret_key="${1#*=}"; shift ;;
      --data-root=*)           data_root="${1#*=}"; shift ;;
      --milvus-port=*)         milvus_port="${1#*=}"; shift ;;
      --lb-port=*)             lb_port="${1#*=}"; shift ;;
      --etcd-client-port=*)    etcd_client_port="${1#*=}"; shift ;;
      --etcd-peer-port=*)      etcd_peer_port="${1#*=}"; shift ;;
      --minio-api-port=*)      minio_api_port="${1#*=}"; shift ;;
      --pair-port=*)           pair_port="${1#*=}"; shift ;;
      --overwrite)             overwrite=1; shift ;;
      -h|--help)               _cmd_init_help; return 0 ;;
      *)                       die "unknown flag: $1 (try: milvus-onprem init --help)" ;;
    esac
  done

  [[ -n "$peer_ips" ]] || die "--peer-ips is required (comma-separated, e.g. 10.0.0.10,10.0.0.11,10.0.0.12)"

  # Validate peer count: 1 (standalone) or odd >=3.
  local peer_count
  peer_count=$(echo "$peer_ips" | tr ',' '\n' | grep -c .)
  case "$peer_count" in
    1|3|5|7|9) ;;
    *) die "PEER_IPS must have 1 (standalone) or odd >=3 entries; got $peer_count" ;;
  esac

  # Refuse Milvus 2.5 + multi-node up-front. `milvus run standalone` panics
  # on coord election (CompareAndSwap on key=rootcoord) when multiple
  # instances share an etcd; this is an upstream 2.5 limitation. The same
  # check lives in env.sh so any future load also refuses; we mirror it
  # here so operators get the error at init time, not bootstrap time.
  local mv="${milvus_image_tag#v}"
  if [[ "$mv" =~ ^2\.5\. && "$peer_count" -gt 1 ]]; then
    die "Milvus 2.5 + multi-node (CLUSTER_SIZE=$peer_count) is not supported in this build. \`milvus run standalone\` panics on coord election when multiple instances share an etcd; this is an upstream 2.5 limitation, not a milvus-onprem bug. Use Milvus 2.6 for HA (--milvus-image-tag=v2.6.x), or pass --peer-ips=<single-ip> for a 2.5 single-node deploy."
  fi

  # Refuse to clobber existing cluster.env unless --overwrite.
  if [[ -f "$CLUSTER_ENV" && "$overwrite" -ne 1 ]]; then
    die "cluster.env already exists at $CLUSTER_ENV — pass --overwrite to replace it"
  fi

  # Auto-generate MinIO secret if not provided. Print it loudly so the
  # operator knows the value (it must match across all peers).
  local generated_secret=0
  if [[ -z "$minio_secret_key" ]]; then
    minio_secret_key="$(_gen_secret_key)"
    generated_secret=1
  fi

  _write_cluster_env \
    "$peer_ips" "$cluster_name" "$milvus_image_tag" "$minio_secret_key" \
    "$data_root" "$milvus_port" "$lb_port" "$etcd_client_port" \
    "$etcd_peer_port" "$minio_api_port" "$pair_port"

  ok "wrote $CLUSTER_ENV"
  if (( generated_secret )); then
    warn "generated MINIO_SECRET_KEY: $minio_secret_key"
    warn "this exact value must be present in cluster.env on every peer"
    warn "(\`milvus-onprem pair\` distributes it automatically; if syncing manually, copy the file)"
  fi

  host_prep "$data_root"
  ok "init complete. Next: \`milvus-onprem bootstrap\`"
}

_gen_secret_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 18 | tr '/+' '_-'
  else
    head -c 18 /dev/urandom | base64 | tr '/+' '_-'
  fi
}

_write_cluster_env() {
  local peer_ips="$1" cluster_name="$2" image_tag="$3" secret="$4" data_root="$5"
  local milvus_port="$6" lb_port="$7" etcd_client="$8" etcd_peer="$9"
  local minio_api="${10}" pair_port="${11}"

  {
    echo "# ============================================================================="
    echo "# milvus-onprem cluster.env"
    echo "# Generated by 'milvus-onprem init' at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Edit to taste, then re-run: milvus-onprem render && milvus-onprem up"
    echo "# ============================================================================="
    echo ""
    echo "# Topology — comma-separated list of every node's internal IP."
    echo "# Position determines node identity: first IP is node-1, second is node-2, etc."
    echo "PEER_IPS=$peer_ips"
    echo "CLUSTER_NAME=$cluster_name"
    echo ""
    echo "# MinIO credentials (must match across all peers)."
    echo "MINIO_ACCESS_KEY=minioadmin"
    echo "MINIO_SECRET_KEY=$secret"
    echo "MINIO_REGION=us-east-1"
    echo ""
    echo "# Container image versions. Bumping the patch (e.g. v2.6.12) is safe;"
    echo "# bumping major.minor changes which templates/<version>/ directory is used."
    echo "MILVUS_IMAGE_TAG=$image_tag"
    echo "ETCD_IMAGE_TAG=v3.5.25"
    echo "MINIO_IMAGE_TAG=RELEASE.2024-05-28T17-19-04Z"
    echo "NGINX_IMAGE_TAG=1.27-alpine"
    echo ""
    echo "# Data root — all on-disk state under here."
    echo "DATA_ROOT=$data_root"
    [[ -n "$milvus_port"  ]] && echo "MILVUS_PORT=$milvus_port"
    [[ -n "$lb_port"      ]] && echo "NGINX_LB_PORT=$lb_port"
    [[ -n "$etcd_client"  ]] && echo "ETCD_CLIENT_PORT=$etcd_client"
    [[ -n "$etcd_peer"    ]] && echo "ETCD_PEER_PORT=$etcd_peer"
    [[ -n "$minio_api"    ]] && echo "MINIO_API_PORT=$minio_api"
    [[ -n "$pair_port"    ]] && echo "PAIR_PORT=$pair_port"
    echo ""
    echo "# Defaults applied automatically (uncomment to override):"
    echo "# MQ_TYPE=woodpecker          # 2.6: woodpecker | pulsar     2.5: pulsar"
    echo "# MINIO_DRIVES_PER_NODE=1"
    echo "# MILVUS_HEALTHZ_PORT=9091"
    echo "# MINIO_CONSOLE_PORT=9001"
    echo "# WATCHDOG_MODE=monitor       # monitor (alert-only) | auto (3+ nodes)"
    echo "# WATCHDOG_INTERVAL_S=5"
    echo "# WATCHDOG_FAILURE_THRESHOLD=6"
  } > "$CLUSTER_ENV"
  chmod 600 "$CLUSTER_ENV"
}

_cmd_init_help() {
  cat <<EOF
Usage: milvus-onprem init [OPTIONS]

Generate cluster.env and prep the host. Run once per node before bootstrap.

REQUIRED:
  --peer-ips=A,B,C[,...]      Comma-separated IPs of every node in the cluster.
                              Must be 1 (standalone) or odd >=3 (HA).

COMMON OPTIONS:
  --cluster-name=NAME         Cluster identifier. Default: milvus-onprem
  --milvus-image-tag=TAG      Pinned Milvus image. Default: v2.6.11
  --minio-secret-key=KEY      MinIO secret. Auto-generated if omitted.
  --data-root=PATH            On-disk state directory. Default: /data
  --milvus-port=N             Milvus gRPC port. Default: 19530
  --lb-port=N                 nginx LB port (client entry). Default: 19537
  --etcd-client-port=N        Default: 2379
  --etcd-peer-port=N          Default: 2380
  --minio-api-port=N          Default: 9000
  --pair-port=N               HTTP rendezvous port. Default: 19500

OTHER:
  --overwrite                 Replace an existing cluster.env without prompt.
  -h, --help                  Show this help.

For less common settings, edit cluster.env after init.
EOF
}
