#!/usr/bin/env bash
# =============================================================================
# milvus-onprem — PATH wrapper.
#
# Auto-generated by `milvus-onprem install`. DO NOT EDIT BY HAND — re-run
# install from the repo to regenerate. The REPO_ROOT value below is baked
# in at install time so the wrapper finds the correct working tree even
# from elsewhere on the filesystem.
# =============================================================================
exec "${REPO_ROOT}/milvus-onprem" "$@"
